services:
  - type: web
    name: ventify-api
    runtime: dotnet
    plan: free
    buildCommand: dotnet restore && dotnet publish -c Release -o out
    startCommand: cd out && dotnet VentifyAPI.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MYSQL_CONN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://ventify-front.onrender.com
      - key: EPPlusLicenseContext
        value: NonCommercial
